spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis閰嶇疆鏂囦欢鎵€鍦ㄨ矾寰?
  type-aliases-package: springcloud.entity  # 鎵€鏈塃ntity鍒悕绫绘墍鍦ㄥ寘
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper鏄犲皠鏂囦欢
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product-provider #杩欎釜寰堥噸瑕侊紝杩欏湪浠ュ悗鐨勬湇鍔′笌鏈嶅姟涔嬮棿鐩镐簰璋冪敤涓€鑸兘鏄牴鎹繖涓猲ame
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 褰撳墠鏁版嵁婧愭搷浣滅被鍨?
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql椹卞姩鍖?
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8  # 鏁版嵁搴撳悕绉?
    username: root
    password: 123qweASD
    dbcp2:
      min-idle: 5                                # 鏁版嵁搴撹繛鎺ユ睜鐨勬渶灏忕淮鎸佽繛鎺ユ暟
      initial-size: 5                            # 鍒濆鍖栬繛鎺ユ暟
      max-total: 5                               # 鏈€澶ц繛鎺ユ暟
      max-wait-millis: 150                       # 绛夊緟杩炴帴鑾峰彇鐨勬渶澶ц秴鏃舵椂闂
eureka:
  client:
    registerWithEureka: true # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: true # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      #      defaultZone: http://localhost:6001/eureka/
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径显示的是ip地址
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis閰嶇疆鏂囦欢鎵€鍦ㄨ矾寰?
  type-aliases-package: springcloud.entity  # 鎵€鏈塃ntity鍒悕绫绘墍鍦ㄥ寘
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper鏄犲皠鏂囦欢
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-product-provider #杩欎釜寰堥噸瑕侊紝杩欏湪浠ュ悗鐨勬湇鍔′笌鏈嶅姟涔嬮棿鐩镐簰璋冪敤涓€鑸兘鏄牴鎹繖涓猲ame
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 褰撳墠鏁版嵁婧愭搷浣滅被鍨?
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql椹卞姩鍖?
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8  # 鏁版嵁搴撳悕绉?
    username: root
    password: 123qweASD
    dbcp2:
      min-idle: 5                                # 鏁版嵁搴撹繛鎺ユ睜鐨勬渶灏忕淮鎸佽繛鎺ユ暟
      initial-size: 5                            # 鍒濆鍖栬繛鎺ユ暟
      max-total: 5                               # 鏈€澶ц繛鎺ユ暟
      max-wait-millis: 150                       # 绛夊緟杩炴帴鑾峰彇鐨勬渶澶ц秴鏃舵椂闂
eureka:
  client:
    registerWithEureka: true # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: true # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      #      defaultZone: http://localhost:6001/eureka/
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径显示的是ip地址